# Generated by Django 4.2.24 on 2025-10-01 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='event_type',
            field=models.CharField(choices=[('face_recognition', 'Face Recognition'), ('plate_recognition', 'Plate Recognition'), ('unauthorized_access', 'Unauthorized Access'), ('suspicious_activity', 'Suspicious Activity')], max_length=30),
        ),
    ]
