# Generated by Django 4.2.24 on 2025-10-02 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_securityevent_user_alter_securityevent_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=15)),
                ('vehicle_image', models.ImageField(upload_to='vehicle_access/')),
                ('confidence_score', models.FloatField()),
                ('is_authorized', models.BooleanField(default=False)),
                ('access_granted', models.BooleanField(default=False)),
                ('access_type', models.CharField(choices=[('GRANTED', 'Acceso Permitido'), ('DENIED', 'Acceso Denegado'), ('PENDING', 'Pendiente de Validación')], default='PENDING', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('camera_location', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehiclePlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=15, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('AUTHORIZED', 'Autorizado'), ('PENDING', 'Pendiente'), ('REVOKED', 'Revocado')], default='AUTHORIZED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.unit')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plates', to='accounts.vehicle')),
            ],
        ),
    ]
